CREATE TABLE vInfo (
ID int IDENTITY(1,1) PRIMARY KEY,
ScanDate Date,
Customer VARCHAR(255),
VM VARCHAR(255),
Powerstate VARCHAR(20),
Template Bit,
DNS_Name VARCHAR(255), 	
PowerOn	Date,
CPUs INT,
Memory SMALLINT,
NICs INT,
Disks INT,
Network_1 VARCHAR(255),
Resource_pool VARCHAR(255),
Provisioned_MB INT,
In_Use_MB INT,
Unshared_MB INT,
VM_Path VARCHAR(255),
Annotation VARCHAR(255),
Datacenter VARCHAR(255),
Cluster	VARCHAR(255),
Host VARCHAR(255),
OS_config VARCHAR(255),
OS_tools VARCHAR(255),
VM_ID VARCHAR(255),
VM_UUID VARCHAR(255),
VI_SDK_Server_type VARCHAR(255),
VI_SDK_Server VARCHAR(255),
VI_SDK_UUID VARCHAR(255),
);


CREATE TABLE vDisk (
ID int IDENTITY(1,1) PRIMARY KEY,
ScanDate Date,
Customer VARCHAR(255),
VM VARCHAR(255),
Powerstate VARCHAR(20),
Template Bit,
DiskID VARCHAR(255),
Capacity_MB INT,
isRAW BIT,
Disk_mode VARCHAR(255),
Thin BIT,
Eagerly_scrub BIT,
Controller VARCHAR(255),
Unit_num SMALLINT,
disk_Path VARCHAR(255),
);

CREATE TABLE vPartition (
ID int IDENTITY(1,1) PRIMARY KEY,
ScanDate Date,
Customer VARCHAR(255),
VM VARCHAR(255),
Template Bit,
DiskID VARCHAR(255),
Capacity_MB INT,
Consumed_MB INT,
Free_MB INT,
VM_ID VARCHAR(255),
VM_UUID VARCHAR(255),
);
