CREATE TABLE vInfo (
ID int IDENTITY(1,1) PRIMARY KEY,
Scan_ID INT,
Customer VARCHAR(255),
VM VARCHAR(255),
Powerstate VARCHAR(20),
Template Bit,
DNS_Name VARCHAR(255), 	
PowerOn	Date,
CPUs INT,
Memory SMALLINT,
NICs INT,
Disks INT,
Network_1 VARCHAR(255),
Resource_pool VARCHAR(255),
Provisioned_MB INT,
In_Use_MB INT,
Unshared_MB INT,
VM_Path VARCHAR(255),
Annotation VARCHAR(255),
Datacenter VARCHAR(255),
Cluster	VARCHAR(255),
Host VARCHAR(255),
OS_config VARCHAR(255),
OS_tools VARCHAR(255),
VM_ID VARCHAR(255),
VM_UUID VARCHAR(255),
VI_SDK_Server_type VARCHAR(255),
VI_SDK_Server VARCHAR(255),
VI_SDK_UUID VARCHAR(255),
);


CREATE TABLE vDisk (
ID int IDENTITY(1,1) PRIMARY KEY,
Scan_ID INT,
Customer VARCHAR(255),
VM VARCHAR(255),
Powerstate VARCHAR(20),
Template Bit,
DiskID VARCHAR(255),
Capacity_MB INT,
isRAW BIT,
Disk_mode VARCHAR(255),
Thin BIT,
Eagerly_scrub BIT,
Controller VARCHAR(255),
Unit_num SMALLINT,
disk_Path VARCHAR(255),
Datacenter VARCHAR(255),
Cluster	VARCHAR(255),
);

CREATE TABLE vPartition (
ID int IDENTITY(1,1) PRIMARY KEY,
Scan_ID INT,
Customer VARCHAR(255),
VM VARCHAR(255),
Template Bit,
DiskID VARCHAR(255),
Capacity_MB INT,
Consumed_MB INT,
Free_MB INT,
VM_ID VARCHAR(255),
VM_UUID VARCHAR(255),
Datacenter VARCHAR(255),
Cluster	VARCHAR(255),
DATA_CLASSIFICATION VARCHAR(255),
);

CREATE TABLE vHealth (
ID int IDENTITY(1,1) PRIMARY KEY,
Scan_ID INT,
Customer VARCHAR(255),
vmNAME VARCHAR(255),
vmMESSAGE VARCHAR(512),
VI_SDK_Server VARCHAR(255),
VI_SDK_UUID VARCHAR(255),
);

CREATE TABLE vCluster (
ID int IDENTITY(1,1) PRIMARY KEY,
Scan_ID INT,
Customer VARCHAR(255),
ClusterName VARCHAR(255),
Datacenter VARCHAR(255),
NumHosts SMALLINT,
numEffectiveHosts SMALLINT,
TotalCpu INT,
NumCpuCores INT,
NumCpuThreads INT,
Effective_Cpu INT,
TotalMemory INT,
Effective_Memory INT,
HA_enabled BIT,
Failover_Level SMALLINT,
AdmissionControlEnabled BIT,
Host_monitoring VARCHAR(255),
HB_Datastore_Candidate_Policy VARCHAR(255),
VM_Monitoring VARCHAR(255),
DRS_enabled BIT,
DRS_default_VM_behavior SMALLINT,
DRS_vmotion_rate SMALLINT,
VI_SDK_Server VARCHAR(255),
VI_SDK_UUID VARCHAR(255),
);

CREATE TABLE vHost (
ID int IDENTITY(1,1) PRIMARY KEY,
Scan_ID INT,
Customer VARCHAR(255),
Hostname VARCHAR(255),	
Datacenter VARCHAR(255),	
CPU_Model VARCHAR(255),	
Speed SMALLINT,
HT_Available BIT,
HT_Active BIT,
num_CPU SMALLINT,
Cores_per_CPU SMALLINT,
num_Cores SMALLINT,
CPU_usage SMALLINT,
num_Memory INT,
Memory_usage SMALLINT,
num_NICs SMALLINT,
num_HBAs SMALLINT,
num_VMs SMALLINT,
VMs_per_Core SMALLINT,
num_vCPUs SMALLINT,
vCPUs_per_Core SMALLINT,
vRAM INT,
VM_Used_memory INT,
VMotion_support BIT,
Storage_VMotion_support BIT,
Current_EVC	VARCHAR(255),
Max_EVC	VARCHAR(255),
ESX_Version VARCHAR(255),
Domain VARCHAR(255),
DNS_Search_Order VARCHAR(255),
NTP_Servers VARCHAR(255),
Vendor VARCHAR(255),
Model VARCHAR(255),
Service_tag VARCHAR(255),
OEM_specific_string VARCHAR(255),
BIOS_Version VARCHAR(255),
BIOS_Date Date,
Object_ID VARCHAR(255),
VI_SDK_Server VARCHAR(255),
VI_SDK_UUID VARCHAR(255),
);

CREATE TABLE vDatastore(
ID int IDENTITY(1,1) PRIMARY KEY,
Scan_ID INT,
Customer VARCHAR(255),
dsName VARCHAR(255),
dsAddress VARCHAR(255),
Accessible BIT,
dsType VARCHAR(15),
num_VMs SMALLINT, 
Capacity_MB INT,
Provisioned_MB INT, 
In_Use_MB INT,
Free_MB_Free INT,
SIOC_enabled BIT,
SIOC_Threshold SMALLINT,
num_Hosts SMALLINT,
Hosts VARCHAR(1024),
Block_size SMALLINT,
Max_Blocks INT,
num_Extents SMALLINT,
Major_Version VARCHAR(5),
dsVersion VARCHAR(5),
VMFS_Upgradeable BIT,
MHA BIT,
dsURL VARCHAR(255),
VI_SDK_Server VARCHAR(255),
VI_SDK_UUID VARCHAR(255),
);

CREATE TABLE vLicense (
Scan_ID INT,
Customer VARCHAR(255),
LicenseName VARCHAR(255),
LicenseKey	VARCHAR(255),
Labels	VARCHAR(255),
Cost_Unit VARCHAR(255),	
Total smallint,
Used smallint,
Expiration_Date	VARCHAR(255),
Features VARCHAR(1024),
VI_SDK_Server VARCHAR(255),	
VI_SDK_UUID VARCHAR(255),
);

CREATE TABLE vMemory(
Scan_ID INT,
Customer VARCHAR(255),
VM VARCHAR(255),
Powerstate VARCHAR(255),
Template BIT,
Size_MB	INT,
Overhead SMALLINT,	
ramMax INT,
Consumed INT,
Consumed_Overhead SMALLINT,	
ramPrivate INT,
Shared INT,
Swapped INT,
Ballooned INT,
Active INT,
Entitlement INT,
DRS_Entitlement INT,
Shares INT,
Reservation INT,
RamLimit INT,	
Hot_Add	BIT,
VM_ID VARCHAR(255),
VM_UUID	VARCHAR(255),
VI_SDK_Server VARCHAR(255),	
VI_SDK_UUID VARCHAR(255),
Datacenter VARCHAR(255),
Cluster	VARCHAR(255),
);

CREATE TABLE Customers(
ID int IDENTITY(1,1) PRIMARY KEY,
Lead VARCHAR(255),	
Company_Name VARCHAR(255),	
Territory VARCHAR(255),	
CusType VARCHAR(255),	
CusStatus VARCHAR(255),	
CusSite VARCHAR(255),	
AddressLine1 VARCHAR(255),	
City VARCHAR(255),	
CusState VARCHAR(255),	
);

CREATE TABLE Scan_ID(
ID int IDENTITY(1,1) PRIMARY KEY,
Customer_ID int,
ScanDate Date,
);